### ISSUE TITLE
WTH?

### ISSUE THREAD

**Issue by behroozfarkiani** [roadtomsc/Marhoom#1]
It is good to first state your problem clearly and completely. Then analyze its behavior in different instances. Finally, with having a goal in mind, try to design another approach to solve it, if it is necessary.

**Comment by 1995parham** [comment]
😂 😂 
In this program, I try to implement a heuristic way to solve my problem. It has not been completed yet but it has a similar approach to V.Eramo paper.

**Comment by behroozfarkiani** [comment]
What is the point of doing this? You are solving a different problem.

**Comment by 1995parham** [comment]
No this is the same problem. It wants to route chains with considering that they need a manager within their network.

**Comment by behroozfarkiani** [comment]
A subtle change in the objective function, constraints or variables (domains), make a different problem.  There is no point in studying someone else solution approach unless that one is a general framework. Don't waste your time.

**Comment by 1995parham** [comment]
I will check constraints again to make sure there would be no difference in my solution and my heuristic approach. Personally, I want to have a polynomial solution to my problem without any solver so I implemented this.

**Comment by behroozfarkiani** [comment]
>  Personally, I want to have a polynomial solution to my problem without any solver so I implemented this.

> First state your problem clearly and completely. 
> Then analyze its behavior in different instances.
> Finally, with having a goal in mind, try to design another approach to solve it, if it is necessary.
> 

So, where is your complete implementation? where is your analysis? why did you choose to design a 

> polynomial solution to my problem without any solver 

and what are your goals in designing a solution approach? by goals I mean what are the metrics that you will evaluate your algorithm based on?
